services:
  test-suite-frontend:
    image: brapicoordinatorselby/brava-tools-fe:latest
    depends_on:
      - test-suite-backend

  test-suite-backend:
    image: brapicoordinatorselby/brava-tools-be:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    
networks:
    default:
        name: brapi_net
        external: true